### ISSUE TITLE
Update for SCSS

### ISSUE THREAD

**Issue by Jaeiya** [madskristensen/WebEssentials2013#1141]
I'd really appreciate support for the new suffix syntax

http://thesassway.com/news/sass-3-3-released#parent-selector-suffixes

**Comment by jaminroe** [comment]
Sorry to bring this up again, but I'm getting this issue still in VS. I'm on 2013 Update 5. Any ideas what's going on?

![image](https://cloud.githubusercontent.com/assets/1559447/11075128/9215a15e-87c1-11e5-8808-106fc89738d2.png)
