### ISSUE TITLE
Browser Link only updates chrome on mouseover/focus

### ISSUE THREAD

**Issue by gleno** [madskristensen/WebEssentials2013#1165]
For a while now Chrome hasn't been updating when I update my css files, or rather updating as soon as I focus the window or on mouseover/mousemove. By placing the pointer on the chrome window I get jerky updates - not as fast as Firefox or IE. It seems like chrome is doing some kind of painting optimization when the browser is not being interacted with. Is there a way to get the old behavior back?

**Comment by aholmes** [comment]
I'm running version WE `2.5.4` and Chrome `41.0.2272.76 m` and still experiencing this. Can this issue be reopened?
