### ISSUE TITLE
LESS: Undeclared variable / mixin with @import after update to 2.2

### ISSUE THREAD

**Issue by lukeguy99** [madskristensen/WebEssentials2013#1209]
After upgrading to 2.2 I get lots of errors regarding undeclared variables and mixins in my LESS files. I tried to investigate how to reproduce it consistently and it seems the problem is with @import with url syntax, specifically with Google Fonts. My variables and mixins are also imported. If they are declared in the same file, no errors are reported. Also, the LESS is compiled without any errors, this only happens in design time.

For example, I have a `main.less` like this:

```
@import url(http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700|Oswald:400,700&subset=latin,cyrillic-ext,greek-ext,greek,cyrillic,latin-ext);
@import url(http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css);
@import "normalize.css";

@import "mixins";

header {
    background: @headerBackgroundColor;

    .mixin-header;
}
```

Both `@headerBackgroundColor` and `.mixin-header` are declared in `mixins.less`. This gives me errors after opening `main.less` that they are undeclared. If I remove first @import (with font) the errors disappear. If I then return the line, the errors don't appear until I save, close and reopen the file.

The same thing happens if I try to edit the first line. I thought maybe adding `&.css` would help, so after typing it the errors disappear. (Actually, errors disappear as soon as I type a single `.` anywhere in that line). However, they reappear after saving and reopening the file.

I tried to reorder the imports but no matter what, as long as that font import is there, the same issue happens.

**Comment by litera** [comment]
I confirm the problem with mixins having "..." argument notation in Visual Studio 2013 Update 4.

**@madskristensen**: can you please report a bug to the VS team on their TFS?

**Comment by madskristensen** [comment]
Done. It's bug #1104422 in our internal TFS. Thanks for the heads up

**Comment by litera** [comment]
Has anything been done with regards to this bug?
