### ISSUE TITLE
LESS: Support passing rulesets to mixins

### ISSUE THREAD

**Issue by uweg** [madskristensen/WebEssentials2013#1213]
Passing rulesets to mixins (see http://lesscss.org/features/#detached-rulesets-feature ) is not support yet. When i copy the example from the site into the visual studio editor, several warnings show up. Also, the automatic code formatting looks quite ugly.

**Comment by clarkd** [comment]
@madskristensen Do you have a link to that bug? I think I'm seeing the same thing and wondering if it has been fixed since?

**Comment by madskristensen** [comment]
It has not been fixed yet. The bug is internal

**Comment by clarkd** [comment]
Ah okay, thanks for the update.
