### ISSUE TITLE
Context menu mostly grayed out on Web Essentials 2.2

### ISSUE THREAD

**Issue by Rab815** [madskristensen/WebEssentials2013#1219]
When I right click on most js files in my project the context menu is largely grayed out, only JShint and JSCS are not.  Why can't I minify javascript files?  I'm running version 2.2 on VS2013 Update 2.

**Comment by jesslilly** [comment]
![web-essentials-cant-minify](https://cloud.githubusercontent.com/assets/1406490/14561239/efb6ce54-02e2-11e6-9e93-492ee68801fa.png)

I am having the same problem, but this is a brand new js file, there is no corresponding jess2.min.js.

I also have visual studio tools for Node.js installed.  Is there a conflict there?

I tried closing VS already.

**Comment by poojagastya** [comment]
I have the exact same problem as jesslilly .. Tried uninstall > Restart > install > restart without any change
