### ISSUE TITLE
Add wrap option to html bundles

### ISSUE THREAD

**Issue by mralexivy** [madskristensen/WebEssentials2013#1316]
I suggest to add wrapping capabilities to html bundles to keep html file clean and yet allow extended it to use with client side libraries:

Today latest structure in  "*.bundle" is like this:

```
 <files>
    <file>/templates/HtmlPage1.html</file>
    <file>/templates/HtmlPage2.html</file>
  </files>
```

Please update "*.bundle" to support html wrapping:

```
 <files>
   <file path="/templates/HtmlPage1.html">
     <script type="text/ng-template" id="/template1.html">
     </script>
    </file>
    <file path="/templates/HtmlPage2.html">
      <script type="text/ng-template" id="/template2.html">
      </script>
    </file>
  </files>
```

So if for example content of HtmlPage1.html is:

```
<h1>Titlle</h1>
```

With wrapping capabilities the output will be:

```
<script type="text/ng-template" id="/template1.html">
    <h1>Titlle</h1>
</script>
```

which can be really useful.

**Comment by dotnetwise** [comment]
I have added it here -> http://webessentials.uservoice.com/forums/140520-general/suggestions/7927179-add-support-for-liquid-templates-language

+1
