### ISSUE TITLE
compilation failed - Something went wrong reaching ....

### ISSUE THREAD

**Issue by zagros** [madskristensen/WebEssentials2013#1323]
Ever since yesterday's update we're getting this on all machines that updated the nightly build -- we can't compile any less or js files:

```
 7/17/2014 12:19:00 PM: LESS: Compiling home.less
 7/17/2014 12:19:02 PM: Something went wrong reaching: http://127.0.0.1:55577/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:19:06 PM: Something went wrong reaching: http://127.0.0.1:41282/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:19:06 PM: LESS: home.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
 7/17/2014 12:24:52 PM: LESS: Compiling home.less
 7/17/2014 12:24:55 PM: Something went wrong reaching: http://127.0.0.1:24381/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:24:58 PM: Something went wrong reaching: http://127.0.0.1:32955/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:24:58 PM: LESS: home.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
 7/17/2014 12:25:35 PM: LESS: Compiling home.less
 7/17/2014 12:25:36 PM: LESS: Compiling home.less
 7/17/2014 12:25:36 PM: LESS: Compiling home.less
 7/17/2014 12:25:38 PM: LESS: Compiling home.less
 7/17/2014 12:25:39 PM: LESS: Compiling home.less
 7/17/2014 12:25:39 PM: Something went wrong reaching: http://127.0.0.1:8639/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:25:39 PM: LESS: Compiling home.less
 7/17/2014 12:25:39 PM: Something went wrong reaching: http://127.0.0.1:62382/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:25:39 PM: LESS: home.less compilation failed: LESS: Unrecognised input
 7/17/2014 12:25:39 PM: LESS: home.less compilation failed: LESS: Unrecognised input
 7/17/2014 12:25:39 PM: LESS: home.less compilation failed: LESS: Unrecognised input
 7/17/2014 12:25:41 PM: LESS: home.less compilation failed: LESS: Unrecognised input
 7/17/2014 12:25:41 PM: LESS: home.less compilation failed: LESS: Unrecognised input
 7/17/2014 12:25:41 PM: LESS: home.less compilation failed: LESS: Unrecognised input
 7/17/2014 12:25:42 PM: LESS: Compiling home.less
 7/17/2014 12:25:42 PM: LESS: Compiling home.less
 7/17/2014 12:25:43 PM: LESS: Compiling home.less
 7/17/2014 12:25:44 PM: Something went wrong reaching: http://127.0.0.1:41334/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:25:47 PM: Something went wrong reaching: http://127.0.0.1:15693/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:25:48 PM: Something went wrong reaching: http://127.0.0.1:47416/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:25:48 PM: LESS: home.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
 7/17/2014 12:25:49 PM: Something went wrong reaching: http://127.0.0.1:46351/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:25:51 PM: Something went wrong reaching: http://127.0.0.1:41483/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:25:51 PM: LESS: home.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
 7/17/2014 12:25:53 PM: Something went wrong reaching: http://127.0.0.1:18185/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:25:53 PM: LESS: home.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
 7/17/2014 12:26:24 PM: Something went wrong reaching: http://127.0.0.1:34020/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
 7/17/2014 12:26:24 PM: LESS: home.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
 7/17/2014 12:26:24 PM: Something went wrong reaching: http://127.0.0.1:34020/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cstyles.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cstyles.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cstyles.css.map&sourceMapURL&strictMath&
 7/17/2014 12:26:24 PM: Something went wrong reaching: http://127.0.0.1:34020/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cvendors%5Cbootstrap-3.1.1%5Ccss%5Cbootstrap-glyphs.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cvendors%5Cbootstrap-3.1.1%5Ccss%5Cbootstrap-glyphs.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cvendors%5Cbootstrap-3.1.1%5Ccss%5Cbootstrap-glyphs.css.map&sourceMapURL&strictMath&
 7/17/2014 12:26:24 PM: Something went wrong reaching: http://127.0.0.1:34020/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cvars.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cvars.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cvars.css.map&sourceMapURL&strictMath&
 7/17/2014 12:26:24 PM: LESS: styles.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
 7/17/2014 12:26:24 PM: LESS: vars.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
 7/17/2014 12:26:24 PM: LESS: bootstrap-glyphs.less compilation failed: The service failed to respond to this request
            Possible cause: Syntax Error!
```

**Comment by KirschnerMatt** [comment]
This is still an issue for me.

I get compilation errors whenever I attempt to save a .scss file with syntax errors. Even after fixing the syntax, I still get the compilation errors and am forced to restart VS.

**Comment by Mshael9** [comment]
> Ever since yesterday's update we're getting this on all machines that updated the nightly build -- we can't compile any less or js files:
> 
> ```
>  7/17/2014 12:19:00 PM: LESS: Compiling home.less
>  7/17/2014 12:19:02 PM: Something went wrong reaching: http://127.0.0.1:55577/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:19:06 PM: Something went wrong reaching: http://127.0.0.1:41282/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:19:06 PM: LESS: home.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
>  7/17/2014 12:24:52 PM: LESS: Compiling home.less
>  7/17/2014 12:24:55 PM: Something went wrong reaching: http://127.0.0.1:24381/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:24:58 PM: Something went wrong reaching: http://127.0.0.1:32955/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:24:58 PM: LESS: home.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
>  7/17/2014 12:25:35 PM: LESS: Compiling home.less
>  7/17/2014 12:25:36 PM: LESS: Compiling home.less
>  7/17/2014 12:25:36 PM: LESS: Compiling home.less
>  7/17/2014 12:25:38 PM: LESS: Compiling home.less
>  7/17/2014 12:25:39 PM: LESS: Compiling home.less
>  7/17/2014 12:25:39 PM: Something went wrong reaching: http://127.0.0.1:8639/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:25:39 PM: LESS: Compiling home.less
>  7/17/2014 12:25:39 PM: Something went wrong reaching: http://127.0.0.1:62382/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:25:39 PM: LESS: home.less compilation failed: LESS: Unrecognised input
>  7/17/2014 12:25:39 PM: LESS: home.less compilation failed: LESS: Unrecognised input
>  7/17/2014 12:25:39 PM: LESS: home.less compilation failed: LESS: Unrecognised input
>  7/17/2014 12:25:41 PM: LESS: home.less compilation failed: LESS: Unrecognised input
>  7/17/2014 12:25:41 PM: LESS: home.less compilation failed: LESS: Unrecognised input
>  7/17/2014 12:25:41 PM: LESS: home.less compilation failed: LESS: Unrecognised input
>  7/17/2014 12:25:42 PM: LESS: Compiling home.less
>  7/17/2014 12:25:42 PM: LESS: Compiling home.less
>  7/17/2014 12:25:43 PM: LESS: Compiling home.less
>  7/17/2014 12:25:44 PM: Something went wrong reaching: http://127.0.0.1:41334/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:25:47 PM: Something went wrong reaching: http://127.0.0.1:15693/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:25:48 PM: Something went wrong reaching: http://127.0.0.1:47416/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:25:48 PM: LESS: home.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
>  7/17/2014 12:25:49 PM: Something went wrong reaching: http://127.0.0.1:46351/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:25:51 PM: Something went wrong reaching: http://127.0.0.1:41483/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:25:51 PM: LESS: home.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
>  7/17/2014 12:25:53 PM: Something went wrong reaching: http://127.0.0.1:18185/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:25:53 PM: LESS: home.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
>  7/17/2014 12:26:24 PM: Something went wrong reaching: http://127.0.0.1:34020/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Chome.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:26:24 PM: LESS: home.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
>  7/17/2014 12:26:24 PM: Something went wrong reaching: http://127.0.0.1:34020/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cstyles.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cstyles.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cstyles.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:26:24 PM: Something went wrong reaching: http://127.0.0.1:34020/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cvendors%5Cbootstrap-3.1.1%5Ccss%5Cbootstrap-glyphs.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cvendors%5Cbootstrap-3.1.1%5Ccss%5Cbootstrap-glyphs.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cvendors%5Cbootstrap-3.1.1%5Ccss%5Cbootstrap-glyphs.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:26:24 PM: Something went wrong reaching: http://127.0.0.1:34020/?service=LESS&sourceFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cvars.less&targetFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cvars.css&mapFileName=C:%5CSource%5CmyConnect%5CmyConnect%5CContent%5Cbljc%5Cvars.css.map&sourceMapURL&strictMath&
>  7/17/2014 12:26:24 PM: LESS: styles.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
>  7/17/2014 12:26:24 PM: LESS: vars.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
>  7/17/2014 12:26:24 PM: LESS: bootstrap-glyphs.less compilation failed: The service failed to respond to this request
>             Possible cause: Syntax Error!
> ```
>

**Comment by Mshael9** [comment]
> Not sure how helpful this is, but when Node crashes due to a syntax error, it throws this error:
> 
> ```
> C:\Users\username\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\fdsafasdf\Resources\nodejs\tools\server\services\srv-scss.js:96
>                 Details: regex.message,
>                               ^
> TypeError: Cannot read property 'message' of null
>     at sass.render.error (C:\Users\username\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\fdsafasdf\Resources\nodejs\tools\server\services\srv-scss.js:96:31)
>     at onError (C:\Users\username\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\fdsafasdf\Resources\nodejs\tools\node_modules\node-sass\sass.js:95:16)
> ```
>
