### ISSUE TITLE
Inconsistent behavior with #region and #endregion inside Razor .cshtml view

### ISSUE THREAD

**Issue by leniel** [madskristensen/WebEssentials2013#1457]
Consider this:

``` JS
// #region Types & Categories

alert('OK');

// #endregion
```

the code above produces a matching #region handle in Visual Studio 2013 editor but as soon as I add some block of jQuery code the region simply stops working, that is, there's no more the little - handle to open and close the region:

``` JS

// #region Types & Categories

$('#UserDefinedType').change(function()
{
    var type = $(this).val();

    var cats = $('#Category');

    cats.prop("disabled", type == "");

    $.ajax({
        url: '@Url.Action("GetCategories", "Base")',
        data: { type: type },
        type: 'GET',
        cache: false,
        success: function(categories)
        {
            cats.empty();

            $.each(categories, function(index, category)
            {
                cats.append($('<option/>', {
                    value: category.Value,
                    text: category.Text
                }));
            });
        }
    });
});

// #endregion

```

See the screenshot:

![2014-08-30_13-39-09](https://cloud.githubusercontent.com/assets/764854/4099591/5f0af6ca-3064-11e4-9acf-61fa59308fd1.png)

**Comment by radubartan** [comment]
**Regions** in razor views _work for me_ in VS 2017.
![yey_region](https://user-images.githubusercontent.com/6721563/54354844-ff2b2100-462d-11e9-9b7c-1171c430fdde.JPG)
