### ISSUE TITLE
Add option to set relativeUrls to true/false in LESS

### ISSUE THREAD

**Issue by Ocelot42** [madskristensen/WebEssentials2013#1465]
Right now relativeUrls is hardcoded to true, it would be nice to have an option to set it to true or false.

For a workaround I changed the value in srv-less.js to false and it worked as I expected.

**Comment by am11** [comment]
I have added `Adjust Relative Paths` option in WE settings. What it does is, if you use `Custom output directory` and `Tools > Web Essentials > [Le/Sa]ss > Adjust Relative Paths` is true, it will perform the replacement throughout the output and resolve relative paths for all `url(`s.
#1893 fixes your issue.
