### ISSUE TITLE
Web Essentials 2013 for Update 4 RC cannot be installed to VS 2013 Express for Web

### ISSUE THREAD

**Issue by seanxlliu** [madskristensen/WebEssentials2013#1629]
WE cannot be installed VS 2013 Express for Web with Update 4 RC during the installing process

11/7/2014 11:23:26 AM - Microsoft VSIX Installer
11/7/2014 11:23:26 AM - -------------------------------------------
11/7/2014 11:23:26 AM - Initializing Install...
11/7/2014 11:23:27 AM - Extension Details...
11/7/2014 11:23:27 AM -  Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
11/7/2014 11:23:27 AM -  Name            : Web Essentials 2013 for Update 4 RC
11/7/2014 11:23:27 AM -  Author          : Mads Kristensen
11/7/2014 11:23:27 AM -  Version         : 2.4
11/7/2014 11:23:27 AM -  Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4 RC
11/7/2014 11:23:27 AM -  Locale          : en-US
11/7/2014 11:23:27 AM -  MoreInfoURL     : http://vswebessentials.com/
11/7/2014 11:23:27 AM -  InstalledByMSI  : False
11/7/2014 11:23:27 AM -  SupportedFrameworkVersionRange : [4.5]
11/7/2014 11:23:27 AM - 
11/7/2014 11:23:27 AM -  Supported Products : 
11/7/2014 11:23:27 AM -   Microsoft.VisualStudio.Pro
11/7/2014 11:23:27 AM -    Version : [12.0.31010]
11/7/2014 11:23:27 AM - 
11/7/2014 11:23:27 AM -  References      : 
11/7/2014 11:23:27 AM -   -------------------------------------------------------
11/7/2014 11:23:27 AM -   Identifier   : Microsoft.VisualStudio.MPF.12.0
11/7/2014 11:23:27 AM -   Name         : Visual Studio MPF 12.0
11/7/2014 11:23:27 AM -   Version      : [12.0,13.0)
11/7/2014 11:23:27 AM -   MoreInfoURL  : 
11/7/2014 11:23:27 AM -   Nested       : No
11/7/2014 11:23:27 AM - 
11/7/2014 11:23:27 AM - 
11/7/2014 11:23:27 AM - Searching for applicable products...
11/7/2014 11:23:27 AM - Found installed product - Microsoft Visual Studio Express 2013 for Web
11/7/2014 11:23:27 AM - Found installed product - Global Location
11/7/2014 11:23:27 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by nisarg18** [comment]
Hi I can not be able to install web essential 2013 to my Visual Studio 2013 ultimate Please Help me.
Install Log is as below


12-09-2015 6:48:38 AM - Microsoft VSIX Installer
12-09-2015 6:48:38 AM - -------------------------------------------
12-09-2015 6:48:44 AM - Initializing Install...
12-09-2015 6:48:47 AM - Extension Details...
12-09-2015 6:48:47 AM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
12-09-2015 6:48:47 AM - 	Name            : Web Essentials 2013.5
12-09-2015 6:48:47 AM - 	Author          : Mads Kristensen
12-09-2015 6:48:47 AM - 	Version         : 2.6.36
12-09-2015 6:48:47 AM - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4 or 5
12-09-2015 6:48:47 AM - 	Locale          : en-US
12-09-2015 6:48:47 AM - 	MoreInfoURL     : http://vswebessentials.com/
12-09-2015 6:48:47 AM - 	InstalledByMSI  : False
12-09-2015 6:48:47 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
12-09-2015 6:48:47 AM - 
12-09-2015 6:48:48 AM - 	Supported Products : 
12-09-2015 6:48:48 AM - 		Microsoft.VisualStudio.Pro
12-09-2015 6:48:48 AM - 			Version : [12.0.31101,13.0)
12-09-2015 6:48:48 AM - 
12-09-2015 6:48:48 AM - 	References      : 
12-09-2015 6:48:48 AM - 
12-09-2015 6:48:48 AM - Searching for applicable products...
12-09-2015 6:48:49 AM - Found installed product - Microsoft Visual Studio 2010 Professional
12-09-2015 6:48:49 AM - Found installed product - Microsoft Visual Studio Express 2012 for Web
12-09-2015 6:48:49 AM - Found installed product - Microsoft Visual Studio Ultimate 2013
12-09-2015 6:48:49 AM - Found installed product - Microsoft Visual Studio Premium 2013
12-09-2015 6:48:49 AM - Found installed product - Microsoft Visual Studio Professional 2013
12-09-2015 6:48:49 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
12-09-2015 6:48:49 AM - Found installed product - Global Location
12-09-2015 6:48:49 AM - Found installed product - ssms
12-09-2015 6:48:50 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by GProulx** [comment]
Do you have installed Update 4 or 5 before trying to install Web Essentials 2013?
