### ISSUE TITLE
Crash when trying to edit element's classes

### ISSUE THREAD

**Issue by ehorodyski** [madskristensen/WebEssentials2013#1631]
I've noticed a weird issue that only started today, even though I've had the nightly build for VS2013 Update 4 for a while. When I try to edit an HTML element's classes (such as adding one to an element that already has classes), Visual Studio crashes. I can (almost) confirm this is from Web Essentials because when I turn the extension off I have no problems editing/removing/adding classes to any HTML file. 

If someone can point me to where a crash file would be printed to on my file system I'd gladly add it to this submission -- I'm just not aware of where it would be. I could also post a video, but I think that's overkill and that the crash log would be better. 

Let me know what more information would be helpful and I'll do my darnest to get it posted here.

**Update 1**: When I try to debug the issue, I get the following error:

``` csharp
System.NullReferenceException was unhandled 
Message: An unhandled exception of type 'System.NullReferenceException' occurred in
Microsoft.VisualStudio.Platform.VSEditor.dll
Additional information: Object reference not set to an instance of an object.`
```

**Comment by omt66** [comment]
I have the same problem. BTW: It is a web project.
