### ISSUE TITLE
Web Essentials will not install in Visual Studio Express for Web 2013.4

### ISSUE THREAD

**Issue by jamescoburn** [madskristensen/WebEssentials2013#1661]
The previous version of Web Essentials 2013 installed just fine (and worked flawlessly) in Visual Studio Express for Web 2013.3.  However, upon installing Update 4, I'm unable to install Web Essentials 2013 for Update 4.  Is this by design?

**Comment by les113** [comment]
Web Essentials 2015.3 v3.0.235.vsix will not install on vs express 2015 for web ver 14.0.25431.01 update 3
