### ISSUE TITLE
Navigate To (CTRL+Comma) crashes with WE installed (2.5.3)

### ISSUE THREAD

**Issue by geoffappleford** [madskristensen/WebEssentials2013#1684]
In a standard Asp.net MVC project, using **Navigate To** to find CSS styles causes VS 2013 to crash.

I suspect its related to issue #1631 (I was also experiencing that problem but recent updates to WE seem to have fixed it)

If I type really slowly, it doesn't crash - it's as if the intellisense needs time to catch up.

Uninstalling WE also fixes the problem.

**Comment by Mystikweb** [comment]
I am seeing similar things in a couple of different solutions I am working in.  All the solutions have ASP.NET MVC/Web API projects in them.

I will not always have the crashing that @geoffappleford is mentioning but I will just have all of the intellisense just stop working on me all together.  If I disable and reenable the extension it will work for a little while but then just stops working again.
