### ISSUE TITLE
JSCS: the disallowleftstickedOperator rule is no longer supported

### ISSUE THREAD

**Issue by marcuslindh** [madskristensen/WebEssentials2013#1718]
Message is displayed on an empty js file, and even files that have code.

![image](https://cloud.githubusercontent.com/assets/5172807/5603303/4a20c6e4-937f-11e4-8605-a720f977eba3.png)

![image](https://cloud.githubusercontent.com/assets/5172807/5603329/6d3600a8-9380-11e4-953b-c388e9af1ed6.png)

I have VS 2013 Update 4

**Comment by am11** [comment]
We don't have that rule in our defaults any more: https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/Resources/settings-defaults/.jscsrc, as this was removed a long time ago: https://github.com/madskristensen/WebEssentials2013/issues/1228. You just need to delete your default `.jscsrc` in your home directory (`%userprofile%`) and on the next save, it will be spawned (copied from WE default settings directory).
