### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by markblin** [madskristensen/WebEssentials2013#1722]
1/5/2015 9:29:21 AM - Microsoft VSIX Installer
1/5/2015 9:29:21 AM - -------------------------------------------
1/5/2015 9:29:21 AM - Initializing Install...
1/5/2015 9:29:38 AM - Extension Details...
1/5/2015 9:29:38 AM - 	Identifier      : 5fb7364d-2e8c-44a4-95eb-2a382e30fec8
1/5/2015 9:29:38 AM - 	Name            : Web Essentials 2013 for Update 4
1/5/2015 9:29:38 AM - 	Author          : Mads Kristensen
1/5/2015 9:29:38 AM - 	Version         : 2.5.3
1/5/2015 9:29:38 AM - 	Description     : Adds many useful features to Visual Studio for web developers. Requires VS2013 Update 4
1/5/2015 9:29:38 AM - 	Locale          : en-US
1/5/2015 9:29:38 AM - 	MoreInfoURL     : http://vswebessentials.com/
1/5/2015 9:29:38 AM - 	InstalledByMSI  : False
1/5/2015 9:29:38 AM - 	SupportedFrameworkVersionRange : [4.5]
1/5/2015 9:29:38 AM - 
1/5/2015 9:29:38 AM - 	Supported Products : 
1/5/2015 9:29:38 AM - 		Microsoft.VisualStudio.Pro
1/5/2015 9:29:38 AM - 			Version : [12.0.31101]
1/5/2015 9:29:38 AM - 		Microsoft.VisualStudio.VWDExpress
1/5/2015 9:29:38 AM - 			Version : [12.0.31101]
1/5/2015 9:29:38 AM - 
1/5/2015 9:29:38 AM - 	References      : 
1/5/2015 9:29:38 AM - 		-------------------------------------------------------
1/5/2015 9:29:38 AM - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
1/5/2015 9:29:38 AM - 		Name         : Visual Studio MPF 12.0
1/5/2015 9:29:38 AM - 		Version      : [12.0,13.0)
1/5/2015 9:29:38 AM - 		MoreInfoURL  : 
1/5/2015 9:29:38 AM - 		Nested       : No
1/5/2015 9:29:38 AM - 
1/5/2015 9:29:38 AM - 
1/5/2015 9:29:38 AM - Searching for applicable products...
1/5/2015 9:29:38 AM - Found installed product - Microsoft Visual Studio Ultimate 2013
1/5/2015 9:29:38 AM - Found installed product - Microsoft Visual Studio Premium 2013
1/5/2015 9:29:38 AM - Found installed product - Microsoft Visual Studio Professional 2013
1/5/2015 9:29:38 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1/5/2015 9:29:38 AM - Found installed product - Global Location
1/5/2015 9:29:38 AM - Found installed product - ssms
1/5/2015 9:29:38 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by madskristensen** [comment]
You need to check Web Development in the VS installer. Modify your VS installation and make sure to check Web Development.
