### ISSUE TITLE
I got this error continously opened in my Visual studio 2013 update 5 ctp1. 

### ISSUE THREAD

**Issue by anirugu** [madskristensen/WebEssentials2013#1725]
here is the screenshot

http://imgur.com/I0o4Y3k

Can someone Look at this bug and help me by make it fix.

I know Installing CTP1 update 5 is my own fault. I just posted it here to help other dev to fix it.

**Comment by am11** [comment]
@madskristensen if I am not wrong, isn't current version of WE tied / locked to VS2013 Update 4?

**Comment by madskristensen** [comment]
Correct. Update 5 support isn't there yet. This is by design
