### ISSUE TITLE
QUESTION: Does build generate a debug version, and is there performance loss?

### ISSUE THREAD

**Issue by RobertinoValue** [madskristensen/WebEssentials2013#1729]
Build output starts with :
```1>------ Rebuild All started: Project: WebEssentials2013, Configuration: Debug Any CPU ------```

Installable is created in a Debug folder :

```Bash
C:\home\robert\visual-studio\2013\ext\webessentials2013\EditorExtensions\bin\Debug\WebEssentials2013.vsix
```

This suggests a debug version is produced.
**Is this the case, and is there any significant performance loss?**
I prefer to run WE self-compiled from the repo, but would not like to give up significant performance for it.

**Comment by madskristensen** [comment]
No, the builds are produced are all release builds

**Comment by RobertinoValue** [comment]
Thanks!
And also a big thanks for WE.
