### ISSUE TITLE
TypeScript 1.4 compiler options

### ISSUE THREAD

**Issue by nycdotnet** [madskristensen/WebEssentials2013#1736]
TypeScript 1 4 was recently released and added several compiler options that were not added to the in-box VS TypeScript build window.  It sounds like the TypeScript team is not interested to add a UI for them, though some are quite handy.  Would you accept a PR to add them to Web Essentials?

See here:

https://github.com/Microsoft/TypeScript/issues/1712#issuecomment-70574319

Thanks.

**Comment by madskristensen** [comment]
No thanks. Issue with these type of features is that the TS team might ship them in an update. We have been burned by this before and it's a lot of work to then remove again.

**Comment by nycdotnet** [comment]
OK thanks.
