### ISSUE TITLE
Preview panes for VS 2015

### ISSUE THREAD

**Issue by bdelaney** [madskristensen/WebEssentials2013#1739]
I had posted this on 2015 repo, but comment there led me to bring it over here.

Reading over the first 11 issues (WE 2015) and note this has been answered, but wanted to '+1' it.

For a project with significant Sass investment, I'm back to using my VS 2013 IDE with WE installed. And it's all because of the Preview pane.

It's not that this is limited to Less and Sass either. I bet lots of folks depend on the preview feature for things like TypeScript and CoffeeScript too.

Just my vote for bringing back the side by side preview pane functionality. Optimistic it will be appear by the time of RTM.

**Comment by madskristensen** [comment]
This bug was already closed on the WE2015 issue tracker. I do monitor that repo very closely. Keeping it here will not impact WE2015 since they are now completely different code bases

**Comment by bdelaney** [comment]
Got it.
After watching your presentation on web tooling in VS 2015 I figured it's simply a matter of setting up my workflow with Grunt-watch. Now I have preview pane functionality.
