### ISSUE TITLE
Context menu ignores JavaScript filenames containing more than one period.

### ISSUE THREAD

**Issue by samkelleher** [madskristensen/WebEssentials2013#1743]
v2.5.3 (WE 2013 update 4).

Similar to Issue #1219 , the context menu that appears when rightclicking a JS file is nearly all greyed out, with the exception of the Minify command.

A file named "app.debug.js" presents no options; while "app-debug.js" works normally.

So it appears that the files that contain more than one period are ignored.

I can understand if "*.min.js" is ignored, but not anything else.

**Comment by am11** [comment]
> with the exception of the Minify command.

Maybe that is the only command that applies in that context? Select two js files and it will enable JS bundle.

Aren't JSHint and JSCS also enabled? 

> while "app-debug.js" works normally.

Can you show the diff?

**Comment by samkelleher** [comment]
Even for a single file; the JSHint and JSCS options are supposed to be available.

The difference between working and non-working scenarios is simply the filename; not the content.

This filename contains *__two__ periods* and doesn't have any options other than minify: `example.file.js`

This filename contains *__one__ period* and has minify, JSHint and JSCS options available in the context menu: `example-file.js`

**Comment by am11** [comment]
This is exactly my point. Your title suggests that it ignores the options which it does not.

>  example.file.js 

Have you actually tested `example.file.js` or anything other than `.debug.js`?

Each menu item has its own filter, for instance jshint option's filter goes like this: [JavaScriptLintReporter.cs#L28-L34](https://github.com/madskristensen/WebEssentials2013/blob/80aab959b15ace7e6042f9edfc866f8407aeda08/EditorExtensions/JavaScript/Linters/JavaScriptLintReporter.cs#L28-L34), which explicitly filters out `.debug.js`. If your rename it to `example.debug2.js` or anything else (other than what we have in filter condition), the related options would appear.

**Comment by samkelleher** [comment]
That's it, the filter is ignoring the `.debug.js` file ending; which is what my sample file is named.

Dot people not use JSHint on unminified code?
