### ISSUE TITLE
If TypeScript file contains references, merge references into output file

### ISSUE THREAD

**Issue by aviatrix** [madskristensen/WebEssentials2013#1746]
I've just started a new project and i've decided to divide some classes into their own files, however it looks like WE doesn't merge the referenced files on top of my main `app.ts` file.

However, if i run `tsc --out app.js app.ts` it merges them as they should. 

Can somebody add this to WE? 
I'm currently looking into the issue and the source of WE, but nothing makes sense to me. :(

**Comment by am11** [comment]
Normally, WE does not intervene with compilers business. Bundling, however, is a separate case and is WE's exclusive feature. On that account, WE supports bundling for typescript. See https://github.com/madskristensen/WebEssentials2013/pull/1349. Note, WE's bundling is different than ASP.NET MVC's.

Hope that suffice your requirement with minor modifications to your workflow.

**Comment by aviatrix** [comment]
Yes, i'm aware of the mvc bundles, but i'm doing a web project ( just html/js/css ) not an mvc one. describing my files in an xml sounds a bit cumbersome and error prone :(

**Comment by am11** [comment]
MVC bundles are different than WE's bundles (which are XML-based). :)

Give it a try. They are not that difficult to handle. @GProulx wrote a very nice documentation here: http://vswebessentials.com/features/bundling. 

HTH.
