### ISSUE TITLE
LESS detached rulesets support

### ISSUE THREAD

**Issue by michaldudak** [madskristensen/WebEssentials2013#1754]
The LESS editor seems not to support passing rulesets to mixins (http://lesscss.org/features/#detached-rulesets-feature). The resulting CSS is fine, but the editor complains. For example:
   
    .placeholder(@rules) {
      &::-moz-placeholder {
        @rules();
      }
    }

    input {
      .placeholder({ color: #07F; });
    }

The above code generates two warnings:
- Missing a property name before the colon (':') in the "(property) : (value)" declaration in line 3
- The function arguments are unclosed, ')' expected in line 8

**Comment by madskristensen** [comment]
This is a VS bug and we're planning on adding it in VS2015

**Comment by michaldudak** [comment]
I hope you mean fixing ;)
Thanks a lot.

**Comment by madskristensen** [comment]
haha, yes :)
