### ISSUE TITLE
.iced Compiling with Vanilla Compiler

### ISSUE THREAD

**Issue by nfcopier** [madskristensen/WebEssentials2013#1755]
I am currently running WE 2013.4 for Visual Studio 2013 Update 4. Compiling files with the .iced file extension is still invoking the vanilla compiler. The most relevant issue/pull request I could find was #372. This resolved an issue where the IcedCoffeeScript compiler overrode the vanilla compiler. Did this fix perhaps break the IcedCoffeeScript compiler? Has a work around been added that I just didn't notice?

**Comment by am11** [comment]
@nfcopier, I am using Web Essentials 2013 v2.5.4 with 2013 Update 4 and can't reproduce this issue. To wit, download our test feature: https://raw.githubusercontent.com/am11/WebEssentials2013/master/WebEssentialsTests/fixtures/iced/source/test.iced and make a copy of this file and rename to `test.coffee`. Open both in VS and hit save to compile. With iced, the result will look something like this: https://github.com/madskristensen/WebEssentials2013/issues/320#issuecomment-31298213, and the `test.coffee` will produce this kind of an output: https://github.com/madskristensen/WebEssentials2013/issues/320#issuecomment-31195929.

Note the latest versions wrap the output inside this wrapper:

```javascript
(function() {
  //...
}).call(this);
```

If you are still facing the issue, please provide [tangible reproduction steps](https://github.com/madskristensen/WebEssentials2013/blob/master/CONTRIBUTING.md#bug-reports): input with expected and actual outputs.

**Comment by nfcopier** [comment]
@am11, Thank you very much for your response. It was quite helpful. The test file compiled exactly as expected, using the correct compiler in both cases.

**Comment by nfcopier** [comment]
As far as I can tell, the .iced file has to be added to a solution as .iced file. If it is added as a .coffee file and its extension is changed from within Solution Explorer to .iced, it still uses the .coffee compiler. If I create the .iced file from Windows Explorer and add it as an existing item to my solution, it compiles with the .iced compiler. So it seems I can't add a new .iced file from within Visual Studio.

**Comment by am11** [comment]
@nfcopier, normally you need to reopen the file once extension is changed in Solution Explorer for ContentType detection to re-kick-in.

**Comment by nfcopier** [comment]
That explains a lot. All that is required is to close the file. I wonder why that never occurred to me...

I appreciate your help.
