### ISSUE TITLE
where is the 2.5.4 release?

### ISSUE THREAD

**Issue by 304NotModified** [madskristensen/WebEssentials2013#1767]
[Visual Studio gallery[(https://visualstudiogallery.msdn.microsoft.com/56633663-6799-41d7-9df7-0f2a504ca361?SRC=VSIDE) says that the latest version is 2.5.4. But the latest release/tag on [GitHub is 2.5.1](https://github.com/madskristensen/WebEssentials2013/tags). 

Where is the code of 2.5.2, 2.5.3 and 2.5.4?

**Comment by madskristensen** [comment]
Changes were made to remove constraints on specific .NET framework versions. I didn't create the tags for those small changes
