### ISSUE TITLE
External scripts are not recognized

### ISSUE THREAD

**Issue by lfnavess** [madskristensen/WebEssentials2013#1797]
JsHint (W117): 'moment' is not defined.

hi, i have several external libraries, that i use in my aplicattions, like moment.js 
i found that for getting intellisence i have to declare it in the begining of the script, the path to the file like this:

/// \<reference path="../jquery/jquery.min.js" />
/// \<reference path="../jqueryui/jquery-ui.min.js" />
/// \<reference path="../moment/moment.min.js" />

it works with jquery, and jqueryui also

this should make the webessentials know where is defined moment, right?
or what aditionals steps i should make to get rid of the messages

**Comment by lfnavess** [comment]
/// \<reference path="../jquery/jquery.min.js" />
/// \<reference path="../jqueryui/jquery-ui.min.js" />
/// \<reference path="../moment/moment.min.js" />

sorry, it seems that i need to scape the code to be able to see it in the comment

**Comment by lfnavess** [comment]
i have not to write the reference it work joust with drag and drop the external script from solution explorer

**Comment by madskristensen** [comment]
JSHint doesn't look at the /// references that VS uses. You need to add a global to the top of your file. See the JSHint documentation http://jshint.com/docs/
