### ISSUE TITLE
Twitter Summary Card invalid key value

### ISSUE THREAD

**Issue by peterblazejewicz** [madskristensen/WebEssentials2013#1807]
I've to fix `twitter:card` type value in the project at work. The `Summary Card with Large Image` key value should be `summary_large_image`, while WE2013 uses `summary_large-image`:

https://github.com/madskristensen/WebEssentials2013/blob/fa001f0737b0ab0a76a3e9fac9d89e6b722d70f3/EditorExtensions/HTML/Completion/TwitterCardCompletion.cs#L17

https://dev.twitter.com/cards/types/summary-large-image

I'll be more than happy to PR fix for this (and propagate to other repos for the other versions)

Thx!

**Comment by madskristensen** [comment]
A PR would be great. Thanks
