### ISSUE TITLE
Source map paths wrong for JavaScript bundles with relative paths.

### ISSUE THREAD

**Issue by runemoennike** [madskristensen/WebEssentials2013#1808]
When JavaScript files are bundled using a relative path, the generated source maps point to files in a wrong directory.

Because our project is published to a subdirectory (e.g www.example.com/folder) we need to remove the initial slash that is added by default to JavaScript files listed in the bundle file. There is no problem in generating the bundled js files, but it causes wrong paths in the source maps (.min.js.map): The files listed are correct, essentially, but their path is wrong. Depending on the machine and project we try this on, we get one of:
- C:/Windows/System32
- C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio%2012.0/Common7/IDE/
- ../../../../../../../Program%20Files%20(x86)/Microsoft%20Visual%20Studio%2012.0/Common7/IDE/

E.g.

```
"sources":["C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio%2012.0/Common7/IDE/app.js", ...]
```

Steps to reproduce:
1. Create new ASP.NET web project.
2. Add 2 JavaScript files.
3. Create bundle from the JavaScript files with minification enabled.
4. Edit bundle file, removing the initial forward slashes from each listed file.
5. Make sure bundles are regenerated.

There's an example project exhibiting the problem here: http://1drv.ms/1ANlaQV .

**Comment by vintem** [comment]
I'm having the same issue here
