### ISSUE TITLE
chocolatey package

### ISSUE THREAD

**Issue by wshirey** [madskristensen/WebEssentials2013#1839]
Would it be possible to have a chocolatey package for the web essentials 2013 vsix package? that way it could be automated to install via BoxStarter for example.

I would be willing to contribute time to create a package, but wanted to check with you first for permission.

**Comment by JoeRall** [comment]
Installing a vsix is built right into chocolatey. You just need to use the following cmdlet

``` ps1
Install-ChocolateyVsixPackage WebEssentials2013Update4 https://visualstudiogallery.msdn.microsoft.com/56633663-6799-41d7-9df7-0f2a504ca361/file/105627/44/WebEssentials2013.vsix
```

WebEssentials2013Update4 is just a human readable string so I can see what's being installed. You can use anything you want, it's arbitrary.

For details on how that cmdlet works, head to the [source](https://github.com/chocolatey/chocolatey/blob/master/src/helpers/functions/Install-ChocolateyVsixPackage.ps1).

The link I'm using for the vsix I got strait from the visual studio gallery. I'm hoping that it doesn't change with new versions (so you'll always be installing the latest version) but I'm not sure.

**Comment by wshirey** [comment]
Awesome. Thanks for the time to point that out!
