### ISSUE TITLE
Lineage.gen virus reported in OptiPng.exe during installation

### ISSUE THREAD

**Issue by DarekDan** [madskristensen/WebEssentials2013#1843]
I have just installed your extension and Windows Defender reportedly caught a malicious software during the install: 

The following error occurred: Error code 0x80508023. The program could not find the malware and other potentially unwanted software on this computer. 

Category: Password Stealer

Description: This program is dangerous and captures user passwords.

Recommended action: Remove this software immediately.

Items: 
file:C:\Users\Darek\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\y3o24dst.j1m\Resources\Tools\optipng.exe

**Comment by am11** [comment]
Cross reference: https://github.com/madskristensen/WebEssentials2013/issues/541.
