### ISSUE TITLE
 JSHint and JSCS errors off by 1 line

### ISSUE THREAD

**Issue by SteveALee** [madskristensen/WebEssentials2013#1845]
Using the Web Essentials I find that the error/warning line numbers are off by one in the JSHint and JSCS error output window. For example the following code (line 1 in the editor)

``` javascript
var http = require('http')
```
gives this error (note line number is 2)

```
Message	1	JsHint (W033): Missing semicolon.	C:\Users\Steve\documents\projects\NodejsWebApp1\NodejsWebApp1\server.js	2	28	
```

Double clicking on the error does got to the correct line in the source so it's just the displayed line number that is off by one

Originally raised at https://github.com/Microsoft/nodejstools/issues/28

**Comment by am11** [comment]
AFAIR, there is no sane way to fix it. For instance, for the case you described; Web Essentials passes VS logger `line: 1`, VS logger increments the line number (for logging?), but when we double click on the Error List item, it highlights the `line# - 1` (i.e. the correct line). 
I doubted myself many times on this one, but after trying fixing it in source, I ended up convincing myself that it is a VS bug.
Nonetheless, I still think there must be some other way to fix it. Will have to figure out how other extensions are managing it.

**Comment by SteveALee** [comment]
Crazy

**Comment by am11** [comment]
Indeed. Seems like Web Essentials is also handling the `Navigate` event (when we double click). [EditorExtensions/Shared/Linters/LintReporter.cs#L140-L170](LintReporter.cs#L140-L170):

```diff
diff --git a/EditorExtensions/Shared/Linters/LintReporter.cs b/EditorExtensions/Shared/Linters/LintReporter.cs
index c6c0cb7..93fc472 100644
--- a/EditorExtensions/Shared/Linters/LintReporter.cs
+++ b/EditorExtensions/Shared/Linters/LintReporter.cs
@@ -141,7 +141,7 @@ private ErrorTask CreateTask(CompilerError error, string message = null)
         {
             ErrorTask task = new ErrorTask()
             {
-                Line = error.Line,
+                Line = error.Line - 1,
                 Column = error.Column,
                 ErrorCategory = Settings.LintResultLocation,
                 Category = TaskCategory.Html,
@@ -165,7 +165,7 @@ private void task_Navigate(object sender, EventArgs e)
             if (task.Column > 0)
             {
                 var doc = (TextDocument)WebEssentialsPackage.DTE.ActiveDocument.Object("textdocument");
-                doc.Selection.MoveToDisplayColumn(task.Line, task.Column);
+                doc.Selection.MoveToDisplayColumn(task.Line + 1, task.Column);
             }
         }
```

The second edit might need to be `task.Line + 2`, can't verify due to the build issue in current master.

**Comment by SteveALee** [comment]
Aha, progress! Thanks :)

**Comment by SteveALee** [comment]
Thanks
