### ISSUE TITLE
BrowserLink spam of XHR on network and then breaks after first Css sync

### ISSUE THREAD

**Issue by RonaldEstacion** [madskristensen/WebEssentials2013#1852]
When i have BrowserLink on and im using WebEssentials, it's spamming request on the network.

Also Css sync breaks and doesnt work anymore after the first sync to visual studio

![Spam of request](http://i.imgur.com/JiVROOf.png)

**Comment by madskristensen** [comment]
It's a VS issue that is being fixed. Not related to Web Essentials, so closing the issue

**Comment by RonaldEstacion** [comment]
Does it mean that the reason why it's breaking the web essentials is because of the VS problem?
