### ISSUE TITLE
build failure behind http proxy server: git clone failed

### ISSUE THREAD

**Issue by japj** [madskristensen/WebEssentials2013#1859]
I am behind an http_proxy which does not support git:// style cloning.
I can git clone through http/https without any issues.

With the current setup, I get a build failure during the MadsKristensen.EditorExtensions.PreBuildTask

npm ERR! git clone --template=C:\Users\japj\AppData\Roaming\npm-cache_git-remotes_templates --mirror git@github.com:am11/pangyp.git C:\Users\japj\AppData\Roaming\npm-cache_git-remotes\git-github-com-am11-pangyp-git-a953a761: ssh: Could not resolve hostname github.com: no address associated with name

**Comment by SLaks** [comment]
Should be fixed by https://github.com/sass/node-sass/pull/943
