### ISSUE TITLE
Typescript output not added to project

### ISSUE THREAD

**Issue by robbaman** [madskristensen/WebEssentials2013#1860]
Maybe I'm just completely overlooking a setting somewhere, but when I add a Typescript file to a project, enter some code and hit save, the .js and .map files are created (no .min.js though), but these files are not added to the project. And are also not nested underneath the .ts file.

Is there any way to make WE (or VS) do this automatically? Now I have to do it manually for each file I create. I'm using Visual Studio 2013 update 4 with Web Essentials 2.5.4

**Comment by RaptorCZ** [comment]
TypeScript is now part of Visual Studio Update 4 and this is expected behavior. All TS files has Build Actions set to TypeScriptCompile and generated files are always included in publish etc. There is no need to include files in solution. Every build all files are recreated.

**Comment by robbaman** [comment]
Ah, I see, that makes total sense. I guess I'll just remove them from project again :)

Thanks alot!
