### ISSUE TITLE
Visual Studio 2013/4 quite instable after installing Web Essentials

### ISSUE THREAD

**Issue by SetTrend** [madskristensen/WebEssentials2013#1874]
Yesterday I have installed the latest Web Essentials version to my Visual Studio 2013 Update 4.

This is the first time I'm using Web Essentials, so I'm mainly evaluating Web Essentials here.

Since installing and working with TypeScript files, My German Windows Server 2008 R2 installation displayed a Bluescreen while saving the TypeScript file and my German Visual Studio hung while I've been trying to set a breakpoint in TypeScript file during debugging.

**Here's some version information, copied from Visual Studio 2013 About box:**

Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51209

Installierte Version: Ultimate

Architecture and Modeling Tools   06181-004-0451022-02857
Microsoft Architecture and Modeling Tools
    
UML® und Unified Modeling Language™ sind Marken oder eingetragene Marken der Object Management Group, Inc. in den Vereinigten Staaten und anderen Ländern.

LightSwitch für Visual Studio 2013   06181-004-0451022-02857
Microsoft LightSwitch für Visual Studio 2013

Rechtschreibprüfung für die Visual Studio 2013-Codeanalyse   06181-004-0451022-02857
Rechtschreibprüfung für die Microsoft® Visual Studio® 2013-Codeanalyse

Teile des International CorrectSpell™-Rechtschreibprüfungssystems © 1993 von Lernout & Hauspie Speech Products N.V. Alle Rechte vorbehalten.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Elektronische Version lizenziert von Lernout & Hauspie Speech Products N.V. Alle Rechte vorbehalten.

Team Explorer für Visual Studio 2013   06181-004-0451022-02857
Microsoft Team Explorer für Visual Studio 2013

Visual Basic 2013   06181-004-0451022-02857
Microsoft Visual Basic 2013

Visual C# 2013   06181-004-0451022-02857
Microsoft Visual C# 2013

Visual C++ 2013   06181-004-0451022-02857
Microsoft Visual C++ 2013

Visual F# 2013   06181-004-0451022-02857
Microsoft Visual F# 2013

Windows Phone SDK 8.0 - DEU   06181-004-0451022-02857
Windows Phone SDK 8.0 - DEU

Allgemeine Azure-Tools   1.4
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

ASP.NET und Webtools   12.4.60425.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Web Apps
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

MainBrain Build Extensions VS2013   1.14
Information about my package

Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 

Microsoft Azure HDInsight HQL Service   2.0.1000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.1000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.6
Microsoft Azure Tools für Microsoft Visual Studio 2013 - v2.6.30423.1601

NuGet-Paket-Manager   2.8.60318.734
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter "http://docs.nuget.org/".

Office Developer Tools für Visual Studio 2013 DEU   12.0.40429
Microsoft Office Developer Tools für Visual Studio 2013 DEU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio-Erweiterung zur Visualisierung aggregierter Zusammenfassungen vom PreEmptive Analytics-Produkt.

Release Management for Visual Studio Package   1.0
Release Management for Visual Studio

SQL Server Data Tools   12.0.50512.0
Microsoft SQL Server Data Tools

VSCommands for Visual Studio 2013   12.0
VSCommands for Visual Studio 2013

Web Essentials 2013   2.5.3
Adds many useful features to Visual Studio for web developers.

Windows Phone 8.1 SDK-Integration   1.0
Dieses Paket integriert die Tools für das Windows Phone 8.1 SDK in die Menüs und Steuerelemente von Visual Studio.

Workflow Manager Tools 1.0   1.0
Dieses Paket enthält die erforderlichen Visual Studio-Integrationskomponenten für Workflow Manager.

**Comment by rjgotten** [comment]
> My German Windows Server 2008 R2 installation displayed a Bluescreen while saving the TypeScript file

Uhm ... user mode processes don't cause BSODs. You have *other* problems ...
