### ISSUE TITLE
Can't scroll within TypeScript preview panels

### ISSUE THREAD

**Issue by SetTrend** [madskristensen/WebEssentials2013#1879]
I don't seem to be able to scroll within TypeScript preview panels. There's neither a scrollbar nor any other way of scrolling the content therein.

Moreover, it's not possible to give focus to the content. Hitting [F6] from source code panel doesn't switch to preview panel, too.

![can t scroll](https://cloud.githubusercontent.com/assets/9283914/8008186/ce3935bc-0ba0-11e5-9f16-8b55e75cf0fc.png)

**Comment by jhurdlow** [comment]
FWIW: You can't zoom the text in the preview with Ctrl-MouseWheel either. As a result of these issues I typically leave it off, and only turn it on if I really need to see what JS it is generating.

**Comment by SetTrend** [comment]
Yeah ... But switching the preview panel off not really the purpose of the preview panel, is it?

I'm new to TypeScript but used to program applications in JavaScript, so I'm very keen to see what JavaScript TypeScript actually generates. Sure, I could open the resulting .js file aside the .ts file editor, which would be analogous to the preview panel. But, again, I suggest to Web Essentials: Either do it correctly or leave it out of the suite.
