### ISSUE TITLE
LESS compiler should not regard empty less file as syntax error

### ISSUE THREAD

**Issue by SetTrend** [madskristensen/WebEssentials2013#1881]
It is very distracting that the LESS preview panel regards empty less files as errors.

I got very confused when I started editing a LESS file and I was searching for some hidden characters (spaces??) for minutes.

**Comment by rjgotten** [comment]
Here's the fix, courtesy of yours truly:
https://github.com/madskristensen/WebEssentials2013/issues/1696#issuecomment-77122202

This is, I think, the fourth time now that I jump in and mention this...

Mads should really **FREAKING FIX THIS** and push out a new stable update of WE 2013. VS 2015 isn't even released yet and he's already all but dropped WE 2013 in favor of WE 2015. Makes it seem as if he's one of those people that only cares about the very latest 'new and shiny'. Bah!

**Comment by SetTrend** [comment]
Gee, thanks, RJ, for pointing to this quick fix.

Life can be so easy ...
