### ISSUE TITLE
Virus detected?

### ISSUE THREAD

**Issue by kgjersda** [madskristensen/WebEssentials2013#1902]
So I just installed Web Essentials through Visual Studio Extensions and this popped up.

![Virus](http://i.imgur.com/gWzoOjv.png)

Scary!

**Comment by kgjersda** [comment]
Cross reference: #1843 , #541

**Comment by madskristensen** [comment]
Closing because it's a duplicate as mentioned above

**Comment by seriema** [comment]
@madskristensen you closed the original #541 without mentioning why, and there's no comment on #1843 either. Would be useful to hear your thoughts on this issue since it's been happening for what seems a long time (and still happening, as I installed WE today).
