### ISSUE TITLE
Grunt Task Runner: Failed to load

### ISSUE THREAD

**Issue by tshaaban** [madskristensen/WebEssentials2013#1903]
In both Visual Studio 2013 and Visual Studio 2015 RC it appears that Grunt fails to load the tasks passed from the bower file. I've removed Grunt and added it to the project and it and I still seem to be getting the same error across three separate devices. I am sure it must be something I am doing wrong, but I can't seem to find it. Has anyone else had this issue? And what have you done to solve it?

Thanks
![faile to load](https://cloud.githubusercontent.com/assets/6116834/8461850/72d86ee2-1ffd-11e5-8b35-963a18e2e673.PNG)

**Comment by madskristensen** [comment]
You need to add a gruntfile.js. See gruntjs.com for how to use grunt

**Comment by tshaaban** [comment]
That was the first thing I added Mads. Any suggestions?

<img width="770" alt="gruntfile" src="https://cloud.githubusercontent.com/assets/6116834/8657245/6a2a69a0-296a-11e5-945c-60765ced2491.PNG">

**Comment by qbressler** [comment]
I'm having the same exact issue with Visual Studio Community 2015

**Comment by VIAJE** [comment]
Me too... I'm having the same exact issue with Visual Studio Community 2015
