### ISSUE TITLE
Bundling .ts files includes original .ts file source instead of the generated .js code

### ISSUE THREAD

**Issue by germgerm** [madskristensen/WebEssentials2013#1909]
vs2013 update 4 / we2013 update 4
### when bundling .ts files, the generated .js file contains the original .ts file source instead of the generated .js code. The .min.js contains essentially garbage.

test.ts : 
```javascript
enum Color222 { Red = 128, Green, Blue };
```

test.js :
```javascript
var Color222;
(function (Color222) {
    Color222[Color222["Red"] = 128] = "Red";
    Color222[Color222["Green"] = 129] = "Green";
    Color222[Color222["Blue"] = 130] = "Blue";
})(Color222 || (Color222 = {}));
;
//# sourceMappingURL=test.js.map
```
bundle.js :
```javascript
///#source 1 1 /Scripts/test.ts
enum Color222 { Red = 128, Green, Blue };
```
bundle.min.js :
```javascript
Color222;Red=128;Green;Blue;
//# sourceMappingURL=bundle.min.js.map
```
I tried uninstalling and re-installing web essentials but it made no difference.

If I change the .js.bundle to include the generated .js files instead of the source .ts files everything works as expected but that defeats the purpose of bundling .ts files.

**Comment by madskristensen** [comment]
.ts file bundling is not supported. Use the `out` compiler flag on the TS compiler instead

**Comment by germgerm** [comment]
thanks - why are we given the option to do something that is not supported ?
seems that this is so close - just picking up the incorrect file extensions
Since this works for sass/less/coffee/... I did try to pull the package to see how the files are being determined but didn't have any luck getting the solution to compile - will take another look at it.
