### ISSUE TITLE
W.E. 2.6.12 and 2.6.13 do not update css bundles

### ISSUE THREAD

**Issue by PerseusTheGreat** [madskristensen/WebEssentials2013#1930]
Hi.
When I click on munu [Web Essentials/Update All Bundles], W.E. does not update any css/js bundles.
Also, when I change and save css/js files, W.E. does not update related bundles.
I'm using VS 2013 U5; Last week, I uninstalled previous version of W.E. then I installed v2.6.12 and repeated this about v2.6.13 yesterday.
This problem occurred since v2.6.12 and has continued on v2.6.13.
If W.E. settings has changed, please, guide me to configure it.

I apologize, I'm beginner in English.

**Comment by zecompadre** [comment]
and marked as solved in https://github.com/madskristensen/WebEssentials2013/issues/1918

:(

**Comment by am11** [comment]
@zecompadre,
* v2.6.13 was made 12 days ago => 743df646966001eeb84752a79b7590d08e6ac9d3.
* #1918 was closed 4 days ago.
* v2.6.13 was released late and it is not listed in https://github.com/madskristensen/WebEssentials2013/releases (which shows which tag/release corresponds to which commit)

**Comment by PerseusTheGreat** [comment]
@am11 
I installed W.E. 2.6.13 because VS2013 notified it as new update for W.E..
I didn't know (and care) about this release information on GitHub.
I am using VS and when it notify me about some updates of its plugins, I trust it and install updates.
Anyway...
I have installed VS2015 and, W.E. 2.6.13 doesn't matter to me now.
Thanks to your considerations.
