### ISSUE TITLE
Web Essentials disabled on VS 2015 start

### ISSUE THREAD

**Issue by codingfreak** [madskristensen/WebEssentials2013#1959]
I use Visual Studio 2015 Enterprise full patched, Web Essentials 2015 0.5.175 and the latest Web Compiler, Bundler & Minifier along with a bunch of other extensions. Suddenly my Web Essentials gets disabled in the extensions (without any dialog). I can enable it for one run and it'll work fine then. The second start of VS will give me a disabled WebEssentials again. 

Interesting: When WebEssentials is disabled the menu is still present in the VS-Main Menu Bar.

**Comment by madskristensen** [comment]
It sounds like a MEF cache corruption. The error has nothing to do with any of these extensions, but with the Visual Studio MEF cache. Try this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

**Comment by Gambero81** [comment]
Hi, i have the same problem, i have tried Clear MEF Component Cache without success..
First run of visual studio WebEssentials is disabled, if i reenable the extension from Extension and Updates window and click to restart visual studio it reload well, but next time i start visual studio the extension is still disabled...

NB. In my case when web essential is disabled, no web essential menu is loaded

There is a log where i can find some info about the problem?

**Comment by opus131** [comment]
I am having the exact same problem in VS2015 Community on Windows 10. But only with WebEssentials and one other extension, called GitDiffMargin. Clearing the MEF cache does not help. Any other ideas how to fix this?

**Comment by flcdrg** [comment]
I've been seeing the same problem. I noticed that the ActivityLog.xml file was logging a couple of errors. One of which was:

Extension will not be loaded because an extension with the same ID '5fb7364d-2e8c-44a4-95eb-2a382e30fec9' is already loaded at C:\USERS\DAVID\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\LG5OBJ45.EKL\...
          C:\USERS\DAVID\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\PMHVMCOV.BWZ\

Somehow I've ended up with two instances of Web Essentials in separate folders - 0.5.175 and 0.5.197.

Interestingly I've got this for 3 other extensions.

One unusual thing I have done is upgrade from Professional to Enterprise, so not sure if that is significant.

**Comment by flcdrg** [comment]
That was the problem. Solution was to uninstall the extension twice before reinstalling it. I've written up the steps here - http://david.gardiner.net.au/2015/11/web-essentials-2015-extension-keeps.html

**Comment by opus131** [comment]
Thank you very much for this David!

**Comment by zsoltilles** [comment]
I have been struggling with this problem for a while. Thanks David!

**Comment by jphellemons** [comment]
Thank you @madskristensen for https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd
I have a lot of MEF cache issues. Which result that I am unable to open any razor (cshtml) files. So I use Code for razor views and Visual Studio for models/viewmodels/controllers etc.

**Comment by drewnoakes** [comment]
This tool helped me clear up duplicate extensions: https://github.com/remcoros/DuplicateExtensionFinder

**Comment by mttmccb** [comment]
Thanks @drewnoakes I've been having this problem for ages and this has been the only "solution" that worked. It explains why people have success with reinstalling, but so glad I don't have to do that!

**Comment by GlynP** [comment]
Thanks @drewnoakes Came across your helpful VS tool after an exchange with @madskristensen on twitter pointed me to the known VS2015 issue with extensions. No more daily fiddling and checking extension status now! One happy olde programmer :-)

**Comment by drewnoakes** [comment]
@GlynP glad to hear it helped you too, though I can't take credit for the tool as I didn't write it! All credit to @remcoros :)

**Comment by GlynP** [comment]
@drewnoakes Ah, so busy wrestling with the glitch and happy to find a fix I didn't notice you weren't the author! My thanks to you for pointing me in the right direction and my thanks to @remcoros for writing the code.
