### ISSUE TITLE
Chrome not showing SCSS rules, only CSS?

### ISSUE THREAD

**Issue by jaminroe** [madskristensen/WebEssentials2013#1977]
I tried following the instructions on this page to get mapping working: http://www.sitepoint.com/using-source-maps-debug-sass-chrome/. I'd love to get the SCSS files to show up in the Elements tab so I can edit them live like shown in the link above. Or is this not possible with using only Web Essentials? It keeps only showing the .css rules, not .scss in the Styles panel. :disappointed: 

I'm also guessing, because I'm relying on a Visual Studio plug-in, and not running things through Grunt, Gulp or something similar with the browser, it's also not working? I'm very frustrated here... The latest version of Chrome also has support for this built-in now too, so no idea why this isn't working out of the box - https://developers.google.com/web/tools/chrome-devtools/iterate/inspect-styles/edit-styles#edit-sass-less-or-stylus

Any help would be greatly appreciated. Thank you!

**Comment by jaminroe** [comment]
Seems that the compiled CSS file, is putting the wrong file extension in the source map comment. Should be `.scss` but its `.css`

**Comment by jaminroe** [comment]
Isn't fixed in latest version...

**Comment by vishwakarma02** [comment]
If you are using any task runner to compile sass into css then I suggest to try to compile any of scss file into css so that your sass compiler can recreate a scss-map which can be shown by browser to show you scss address in element styles.

**Comment by megaroeny** [comment]
@vishwakarma02 I'm no longer at a company that uses Visual Studio, thank God 🤣
