### ISSUE TITLE
Make Bootstrap validation toggleable

### ISSUE THREAD

**Issue by i7nvd** [madskristensen/WebEssentials2013#1988]
I'm not using Bootstrap in my project, but every time I use a class that has the word "column" in it, Web Essentials underlines it in green to tell me to add other bootstrap-compatible classes. It's also trying to give me suggestions for Bootstrap classes that I won't use. I understand how it can be useful, but I can't find a way to turn it off when it's not relevant. Am I missing something?

**Comment by GProulx** [comment]
Hi,

You can disable bootstrap validation on the Web Essentials Options:
![image](https://cloud.githubusercontent.com/assets/1680372/13017399/fae2f604-d191-11e5-96c5-fd85d715630d.png)

And for the suggestions, I suppose you have Bootstrap css files in your project. Visual Studio (not WE) scan for all CSS files to propose you CSS classes. Deleting them will fix your problem.
