### ISSUE TITLE
MAP files in Google Chrome not working

### ISSUE THREAD

**Issue by PeterMacko** [madskristensen/WebEssentials2013#1993]
Dear all,

i have problem with Google chrome and map files generated from Web Essentials. Files are encoded with UTF8 with BOM but Chrome does not accespt this encoding for map files. Is it possible to change this behavior to encode map files as UTF8 without BOM or ANSII? Is there any workaround how to achieve right behavior in Google Chrome.

**Comment by DorkForce** [comment]
Following.  I have seen this error, too, although I am using WE2015 with Web Compiler 1.10.306.  I actually (3 weeks) recently set up my development machine and at that time did successfully see the mappings working.  Now, starting yesterday, I'm getting the "Failed to parse SourceMap" error in Chrome Devtools.

**Comment by karaliunas** [comment]
I have the same problem too and it's annoying, because it disturbs to work normally with developer tools.

**Comment by helldone1986** [comment]
i have a same problem

**Comment by KucherenkoZZZ** [comment]
Same here, failed to parse fullpage.js source map, plugin dont work on mobile :( 
Hope we have solution in near future!

**Comment by platinumapps** [comment]
Please go and star this issue so it can get resolved: https://bugs.chromium.org/p/chromium/issues/detail?id=611328&q=Failed%20to%20parse%20SourceMap&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by PeterMacko** [comment]
You can close this issue. New Chrome 52 has fix for this problem. This is stackowerflow thread about it: http://stackoverflow.com/questions/36133715/google-chrome-failed-parsing-sourcemap-css-map-web-essential/36151078#36151078 and this is chrome issue report https://bugs.chromium.org/p/chromium/issues/detail?id=611328.
