### ISSUE TITLE
Web Essentials extensions for browser link (inspect, design, etc.) not working for all pages

### ISSUE THREAD

**Issue by kkara** [madskristensen/WebEssentials2013#211]
Hi guys,

This is a weird problem that's giving me lots of headache. I've installed VS2013 RTM and Web Essentials. On a vanilla ASP.NET project I get the inspect and design buttons of the web essentials toolbar to work perfectly. On an existing project that we have though I can't get those to work on all pages. The intesresting thing is that they work on some pages! The pages they're working on are old .aspx pages (the project has mixed legacy ASPX and MVC3 code), but I can't get them to work on the MVC pages.

Here's the thing. There is only one visible difference that I can spot, on the aspx pages I can see the following being added by browser link:

```
   <script type="application/json" id="__browserLink_initializationData">
        {"appName":"Chrome","requestId":"0f71c223c49b42a6a3b4e84fc78aac83"}
   </script>
```

On the pages that don't work, the requestId is missing:

```
      <script type="application/json" id="__browserLink_initializationData">
           {"appName":"Chrome"}
      </script>
```

I've tried with various browsers and it's always the same. On the pages that don't work, when I press the Inspect or Design button, the overlay appears but moving over any element does not select it with the blue border that I see on the pages that do work. A thing to note is that browser link is in general working, since I can actually refresh the browser pages from visual studio.

Any idea of what could be happening and why that requestId isn't there?

Cheers,
Kosta

**Comment by SentinalBais** [comment]
Hi I am seeing the same issue 

Design and Inspect are not working on mvc pages. 
The requestID is missing like the OP Mentioned.

I am using VS2013 Update 5, with version 2.6.36, windows 10 x64

Was there are resolution or workaround for this issue?

**Comment by SentinalBais** [comment]
I am getting the following error when using page inspector
No mapping data was returned from the server
https://msdn.microsoft.com/en-us/library/jj204395.aspx
I think this issue might be related to what is causing page inspector to fail.
