### ISSUE TITLE
Error (0x80070057) shown in Output window after build with solution has solution folders.

### ISSUE THREAD

**Issue by thinbeast** [madskristensen/WebEssentials2013#212]
Every time after I build my solution, I will get the following error:

11/15/2013 12:33:02 PM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()

In VS2013 version I even got multiple errors after build.

After looking for some posts, I believe it's related to the fact that my solution have quite a few solution folders and the code is taking solution folders as projects and try to get properties from it which will fail. The solution also have projects that are not in solution folder but they will always shown below solution folders.

**Comment by mikepoole72** [comment]
I had this in v3.8 and had to build each of my projects separately and then did a full build of all projects. Problem disappeared then.
