### ISSUE TITLE
Bundling is corrupting CSS

### ISSUE THREAD

**Issue by jstanhouse** [madskristensen/WebEssentials2013#225]
I installed the newest update today(11/18/2013) and now when I update my css bundle it is corrupting my css.

Here is the section in my original css:

.autocomplete-w1 {
    background: url('shadow.png') no-repeat bottom right;
    position: absolute;
    top: 0px;
    left: 0px;
    margin: 8px 0 0 6px;
}

and here is the section in my bundled css:

.autocomplete-w1 {
    background: url('shadoshadow.pngepeat bottom right;
    position: absolute;
    top: 0px;
    left: 0px;
    margin: 8px 0 0 6px;
}

I am running VS 2013 Professional on Windows 7.

Thanks for the help.

**Comment by larza79** [comment]
I have come across a similar issue in my project. 

Original css:
table.table thead .sorting { background: url('../images/sort_both.png') no-repeat center right; }
table.table thead .sorting_asc { background: url('../images/sort_asc.png') no-repeat center right; }
table.table thead .sorting_desc { background: url('../images/sort_desc.png') no-repeat center right; }

table.table thead .sorting_asc_disabled { background: url('../images/sort_asc_disabled.png') no-repeat center right; }
table.table thead .sorting_desc_disabled { background: url('../images/sort_desc_disabled.png') no-repeat center right; }

Bundled css:
table.table thead .sorting { background: url('../../Content/DataTables-1.10.3/images/sort_both.png no-repeat center right; }
table.table thead .sorting_asc { background: url('../../Content/DataTables-1.10.3/images/sort_asc.png no-repeat center right; }
table.table thead .sorting_desc { background: url('../../Content/DataTables-1.10.3/images/sort_desc.png no-repeat center right; }

table.table thead .sorting_asc_disabled { background: url('../../Content/DataTables-1.10.3/images/sort_asc_disabled.png no-repeat center right; }
table.table thead .sorting_desc_disabled { background: url('../../Content/DataTables-1.10.3/images/sort_desc_disabled.png no-repeat center right; }

As you can see, each image url is missing their " ') ". The bundle is located in the "/Styles/bundles"-folder, whilst the images are located in the "/Content/DataTables-1.10.3/images"-folder. When the bundle and the original css is in the same folder, everything works just fine.

I am using version 2.3.
