### ISSUE TITLE
LESS Compile on Build not working

### ISSUE THREAD

**Issue by MisinformedDNA** [madskristensen/WebEssentials2013#319]
Created a new web project in VS2013. 
Check that Compile on Build is checked. Tools, Options, Web Essentials, LESS
Added a LESS file
Built project
Checked the destination directory

EXPECTED: CSS file found
ACTUAL: CSS file not found

Notes: 
Using Web Essentials 1.4.1
Opening the LESS file and then saving it causes the CSS to be generated as expected.

**Comment by zsmorris** [comment]
Except that I and a lot of other people don't care about Bootstrap.  Why distort the behavior of the tool just for some specific product?  A better solution would be to have some "ignore this LESS over here" options to the tool.  

The current behavior is really counter-intuitive and kind of useless, for the reasons described by MisinformedDNA comment on Dec 16, 2013.
