### ISSUE TITLE
Iced coffee and deferrals

### ISSUE THREAD

**Issue by ghorsey** [madskristensen/WebEssentials2013#320]
I've updated to vs 2013, now all my coffee script files are breaking.

Is there a way to disable iced cofee?

I have the following function:

```
  this.isAvailable = (type, value) ->
    deferred = $q.defer()

    $http.get(prApiRoot + "users/available?" + type + "=" + value)
        .success((data) ->
            deferred.resolve(data)
            return
        ).error((data, status) ->
            deferred.reject({ data: data, status: status})
            return
        )
    return deferred.promise
```

And it's compiling as:

```
this.authenticate = function(credentials) {
    var deferred;
    deferred = $q.defer({
      lineno: 5,
      context: __iced_deferrals
    });
    $http.post(prApiRoot + "users/authenticate", credentials).success(function(data) {
      deferred.resolve(data);
    }).error(function(data, status) {
      deferred.reject({
        data: data,
        status: status
      });
    });
    return deferred.promise;
  };
```

I'm gettting a run time error because `__iced_deferrals` does not exist.

Is there a way to disable this?  The settings `CoffeeScriptEnableIced` doesn't seem to be present in 2013.

**Comment by UnnDunn** [comment]
For anyone still struggling with this, an easy workaround is to use backticks (`) around the statement containing the defer keyword. This will cause IcedCoffeeScript to treat it as JavaScript and pass it through unmodified. For example:

    deferred = `$q.defer()`

compiles to

```javascript
var deferred;
deferred = $q.defer();
```

**Comment by JustinJmnz** [comment]
@am11  @madskristensen Is there any plans to include this change into Web Compiler?

There's an [active issue there](https://github.com/madskristensen/WebCompiler/issues/202) which is very similar/the same as this.
