### ISSUE TITLE
CoffeeScript: Scrollbar missing in preview pane

### ISSUE THREAD

**Issue by am11** [madskristensen/WebEssentials2013#374]
Despite the fact we can vertically scroll in preview pane of CoffeeScript / IcedCoffeeScript, the scroll bar itself is not visible.

**Comment by rcollette** [comment]
Why was this issue closed?  I'm on WebEssentials 2013 2.5.4 and I don't see a scroll bar for the TypeScript preview pane?

**Comment by am11** [comment]
@rcollette, because this was a VS issue. All classes are `internal` in JSLS.dll in VS2013. Perhaps this will change in VS2015, I haven't tested the code against VS2015 though (note that WE2015 has a separate repo).

**Comment by madskristensen** [comment]
I haven't heard of any changes coming to this in VS2015
