### ISSUE TITLE
LESS fails to compile when source maps is enabled in settings

### ISSUE THREAD

**Issue by madskristensen** [madskristensen/WebEssentials2013#378]
Here's the error message I get:

Compile Error. 
See error list for details
LESS: lessc: ENOENT, open 'C:\Users\madsk\Documents\Visual Studio 2013\Projects\WebApplication20\WebApplication20\Content--source-map-basepath=C:\Users\madsk\Documents\Visual Studio 2013\Projects\WebApplication20\WebApplication20'

**Comment by as671211** [comment]
i am getting this error while i am trying to install less through command prompt in Linux lessc: ENOENT, open '/home/ashish/styles.less'
