### ISSUE TITLE
optipng.exe detected as malware by Windows Defender

### ISSUE THREAD

**Issue by jcgillespie** [madskristensen/WebEssentials2013#541]
Windows Defender has detected the bundled optipng.exe as malware in the last two updates. This happened to me for version 1.7.1 and 1.7.2.

It is detecting it as a password stealer: PWS:Win32/Lineage.gen!C.dam

This was detected by real-time protection during the update process. Virus/Spyware definitions were both at 1.165.2277.0 at the time of the second detection.

Here's a screenshot of windows defender
![windefend](https://f.cloud.github.com/assets/1760760/1956414/a24ce4f0-81f7-11e3-8f89-a375fc0fe059.PNG)

and another of the folder to show that the crazily named folder, 03lucxn4.fjq, really is Web Essentials.

![folder](https://f.cloud.github.com/assets/1760760/1956413/a24bdc2c-81f7-11e3-8bf8-e2bc8e0bfb45.PNG)

![definitions](https://f.cloud.github.com/assets/1760760/1956446/211caebe-81f8-11e3-9a1e-a604dcd3f379.PNG)

Let me know if there is any additional information I can supply.

**Comment by datanotion** [comment]
Bah - this just happened to me again with the 2.5.3.1 WE build and the System Center Endpoint Protection 1.191.3403.0 virus definition db.  Bummer!

**Comment by noamkfir** [comment]
This just happened to me while updating WE for VS 2015 to 0.2.26.

The bug should be reopened as it does not seem to have been resolved.

**Comment by csharpengineer** [comment]
As of today, this is still being found in Forefront Endpoint Protection 2010 (and probably Windows Defender).
