### ISSUE TITLE
Browser Link code injected even when selected "false" in Visual Studio

### ISSUE THREAD

**Issue by DavidVujic** [madskristensen/WebEssentials2013#550]
I have set "Enable Browser Link menu" to false in "Tools -> Options -> Web Essentials", but the code still is injected in the html as long as Visual Studio is running. I think the false option should turn off the feature. The Browser Link menu is actually hidden, but the code is still there in the web page.

I use IIS and have a host mapping to the local site, using Visual Studio 2013 update 1 and Web Essentials 1.7.2.

**Comment by balangninad** [comment]
**
 sessionState cookieless="true"

**
if you have this section in web.config comment it it will work !
