### ISSUE TITLE
ERROR: Can't parse config file: //my solution folder//.jshintrc

### ISSUE THREAD

**Issue by litera** [madskristensen/WebEssentials2013#626]
I'm getting an error when providing global _.jshintrc_ configuration file. Content of this file is extremely simple and shouldn't result in an error:

```
{
    globals: {
        $: false,
        jQuery: false,
        angular: false
    },
    undef: true
}
```
#### Things I've tried
1. setting individual `globals` to `true`.
2. providing individual `globals` as strings eg. `"$": false`
3. renaming _.jshintrc_ file to _config.jshintrc_ which picked it up but still wasn't able to parse it

Nothing seems to work. Web Essentials' JSHint still can't parse this file.
### Additional important question

If we create your own _.jshintrc_ file, do we have to provide **all options** or does JSHint parser take original default optinos and overrides those provided in custom _.jshintrc_ file?

**Comment by leotm** [comment]
Thanks @am11, I arrived here because [SublimeLinter-jshint](https://github.com/SublimeLinter/SublimeLinter-jshint) meant `"indent": 1` not `indent: 1`.
