### ISSUE TITLE
Design/Inspect Does Not Work with Asp.net Web forms

### ISSUE THREAD

**Issue by ghost** [madskristensen/WebEssentials2013#840]
I suspect that this is a known issue, but based on the //BUILD/ conference I am surprised that it occurred. I tried to use the design/inspect tools with a site that had web forms associated and received an error indicating that it was not possible.

**Comment by NLababidi** [comment]
@Yecats Thank you very much for pointing that out "if I load the page and pick the inspect tool first I can inspect without getting an error."

This helped a lot. Thank you
