### ISSUE TITLE
Re-Minify all js files not working

### ISSUE THREAD

**Issue by drebrez** [madskristensen/WebEssentials2013#879]
hi,
I'm using the 1.9 version and if I click Re-Minify all js files from the main WE menu, in the status bar I read the message "Web Essentials: Minifying files..." for a couple of seconds, but nothing is done.
Looking at the code I founded something that can be strange:
in EditorExtensions/Misc/MenuItems/BuildMenu.cs line 86-92 is called MinificationSaveListener.ReMinify with the third parameter (forceSave) as false.
the ReMinify function in EditorExtensions/Misc/Minification/MinificationSaveListener.cs line 41, it will return if forceSave is set to false.
Is it the normal behavior or is a bug?
I'm doing something wrong to make Re-Minify all functionality work? I have to configure extra settings?

Thanks in advance

**Comment by JonyGreen3** [comment]
you can try this free <a href="http://www.online-code.net/minify-js.html">online js minifier</a>, it's using Yui compressor tool.
