### ISSUE TITLE
Sass and TFS

### ISSUE THREAD

**Issue by twilly86** [madskristensen/WebEssentials2013#881]
How does everyone handle SASS and TFS version control?  I work on a team of 4 where we are all modifying sass files and checking into TFS.  We are getting a huge amount of conflicts on sourcemap files and on compiled css files.

I've tried implementing this solution, but the process still requires a lot of manual intervention which then causes problems.
http://windperson.wordpress.com/2013/12/19/visual-studio-sass-compile-msbuild-task/

I can get the sass build working on the server, however web essentials overrides tfignore settings.  I tried to ignore all .css and .css.map files however when Web Essentials saves a new .scss file, it auto creates the .css file and then adds it to source control, overriding the  ignore settings in .tfignore.  Then I need to manually back out the TFS add.

Ideal solution would be to generate .css and .css.map files locally, add them to the project, do not add them to source control, and then have the build re-generate the .css and .css.map files on the build server.  I have this working except for un-doing the add to source control.

Thanks!

**Comment by GaryB432** [comment]
Any further thoughts on this?  What is the best practice workflow for TFS and Web Essentials SCSS? I think I want the .css and .map files excluded from my csproj (and therefore from TFS), then my SCSS processed on my TFS build server as part of my build. (How? Install Web Essentials on the TFS build server?  Make/find a msbuild target? Use node.js and another pre-processor on the build server? Should I be advocating switching our large asp.net development operation to newer tools like node and gulp? Or can we make TFS work with Web Essentials SCSS?)

**Comment by joneff** [comment]
You don't really need WE installed on the build machine, rather you need a Scss compiler. I've found [darrenkopp/libsass-net](/darrenkopp/libsass-net) particularly useful.

On excluding files... You could delete all your current css/map files and disable the compilation of Scss in WE to produce both .css and .map files. Also, make sure you enable "view hidden files" (or something similar) in the project explorer, so you can find any stray .css files that might have snuck back into your project.

My personal workflow is to have both Scss and Css files under source control with no compile action both in the project (wilcard <None />) and WE. I use the console ruby version to compile the files and then checkin the compiled files. That saves me lots of time, as I happen to have a couple of hundred files in the project and I don't want them compiled on build.

**Comment by am11** [comment]
+1, @darrenkopp's libsass-net uses the latest version of libsass (current stable v3.1.0) as the node-sass. (omitting node-sass' alphas and betas). Also libsass-net is used by Sass Studio and many more places.
