### ISSUE TITLE
"The parameter is incorrect" error messages appear in output window after build

### ISSUE THREAD

**Issue by markheath** [madskristensen/WebEssentials2013#91]
Running VS2012 on Win 7, and get strange messages in the output window after every build. I'm assuming that WebEssentials is the cause due to the MadsKristensen namespace. The projects being built have no web components to them at all (WindowsForms)

The following error appears four times during a build:

```
02/10/2013 10:11:51: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
```

**Comment by jotabe-net** [comment]
@madskristensen I have the same problem with WE 2012 3.8, and the problem solved using the same technique exposed in the previous @bbrewder's comment (particularly Rebuilding the whole solutipn from the context menu). I have a big solution, with some 30 errors,a dn use R#,and have installed VS Commands. The error is not consistent, happens from time to time. Is there any other way I can help?

**Comment by ssimontis** [comment]
@madskristensen I am also experiencing this issue, it just started happening in a solution that has been working fine for about 2 months now. It began after I had done a Clean and Build, I tried a Rebuild and that did not work. I am running the latest stable version of WE in VS 2012 with latest service pack, I also run Resharper, nCrunch, and a few other extensions. If there is more info I can provide please let me know.
