### ISSUE TITLE
TagAggregator crashing in VS 2013 (17 Apr 14 nightly build)

### ISSUE THREAD

**Issue by geek-actual** [madskristensen/WebEssentials2013#946]
Getting a error in Web Essentials nightly build from 17 Apr 14 nightly build, information from ActivityLog.xml below.

  <entry>
    <record>1172</record>
    <time>2014/04/18 22:49:56.743</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: sp&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ServiceProvider..ctor(IServiceProvider sp, Boolean defaultServices)&#x000D;&#x000A;   at Microsoft.VisualStudio.Web.HTML.Implementation.ContainedLanguage.ContainedLanguageHostAdapter.Microsoft.Web.Editor.ContainedLanguage.IContainedLanguageHost.get_BufferGraph()&#x000D;&#x000A;   at Microsoft.CSS.Editor.SyntaxCheck.CssErrorTag..ctor(ITextBuffer textBuffer, ICssError error)&#x000D;&#x000A;   at Microsoft.CSS.Editor.SyntaxCheck.CssErrorTagger.CollectTags(SnapshotSpan span, CssErrorList errors, SortedRangeList`1 tagSpans)&#x000D;&#x000A;   at Microsoft.CSS.Editor.SyntaxCheck.CssErrorTagger.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()</description>
  </entry>

**Comment by cottsak** [comment]
I'm getting this too from `\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml`:

```
  <entry>
    <record>771</record>
    <time>2015/03/04 04:22:55.440</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: sp&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ServiceProvider..ctor(IServiceProvider sp, Boolean defaultServices)&#x000D;&#x000A;   at Microsoft.VisualStudio.Web.HTML.Implementation.ContainedLanguage.ContainedLanguageHostAdapter.Microsoft.Web.Editor.ContainedLanguage.IContainedLanguageHost.get_BufferGraph()&#x000D;&#x000A;   at Microsoft.CSS.Editor.SyntaxCheck.CssErrorTag..ctor(ITextBuffer textBuffer, ICssError error)&#x000D;&#x000A;   at Microsoft.CSS.Editor.SyntaxCheck.CssErrorTagger.CollectTags(SnapshotSpan span, CssErrorList errors, SortedRangeList`1 tagSpans)&#x000D;&#x000A;   at Microsoft.CSS.Editor.SyntaxCheck.CssErrorTagger.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()</description>
  </entry>
```

I'm using WebEssentials 2.5.4 in VS13. 

When I can provide repo steps then I will.
